// <auto-generated>
//     Generated by the protocol buffer compiler.  DO NOT EDIT!
//     source: ping.proto
// </auto-generated>
#pragma warning disable 0414, 1591
#region Designer generated code

using grpc = global::Grpc.Core;

namespace Proto.Ping {
  public static partial class Check
  {
    static readonly string __ServiceName = "proto.ping.Check";

    static readonly grpc::Marshaller<global::Proto.Ping.Empty> __Marshaller_proto_ping_Empty = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Ping.Empty.Parser.ParseFrom);
    static readonly grpc::Marshaller<global::Proto.Ping.Pong> __Marshaller_proto_ping_Pong = grpc::Marshallers.Create((arg) => global::Google.Protobuf.MessageExtensions.ToByteArray(arg), global::Proto.Ping.Pong.Parser.ParseFrom);

    static readonly grpc::Method<global::Proto.Ping.Empty, global::Proto.Ping.Pong> __Method_Ping = new grpc::Method<global::Proto.Ping.Empty, global::Proto.Ping.Pong>(
        grpc::MethodType.Unary,
        __ServiceName,
        "Ping",
        __Marshaller_proto_ping_Empty,
        __Marshaller_proto_ping_Pong);

    /// <summary>Service descriptor</summary>
    public static global::Google.Protobuf.Reflection.ServiceDescriptor Descriptor
    {
      get { return global::Proto.Ping.PingReflection.Descriptor.Services[0]; }
    }

    /// <summary>Base class for server-side implementations of Check</summary>
    public abstract partial class CheckBase
    {
      public virtual global::System.Threading.Tasks.Task<global::Proto.Ping.Pong> Ping(global::Proto.Ping.Empty request, grpc::ServerCallContext context)
      {
        throw new grpc::RpcException(new grpc::Status(grpc::StatusCode.Unimplemented, ""));
      }

    }

    /// <summary>Client for Check</summary>
    public partial class CheckClient : grpc::ClientBase<CheckClient>
    {
      /// <summary>Creates a new client for Check</summary>
      /// <param name="channel">The channel to use to make remote calls.</param>
      public CheckClient(grpc::Channel channel) : base(channel)
      {
      }
      /// <summary>Creates a new client for Check that uses a custom <c>CallInvoker</c>.</summary>
      /// <param name="callInvoker">The callInvoker to use to make remote calls.</param>
      public CheckClient(grpc::CallInvoker callInvoker) : base(callInvoker)
      {
      }
      /// <summary>Protected parameterless constructor to allow creation of test doubles.</summary>
      protected CheckClient() : base()
      {
      }
      /// <summary>Protected constructor to allow creation of configured clients.</summary>
      /// <param name="configuration">The client configuration.</param>
      protected CheckClient(ClientBaseConfiguration configuration) : base(configuration)
      {
      }

      public virtual global::Proto.Ping.Pong Ping(global::Proto.Ping.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return Ping(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual global::Proto.Ping.Pong Ping(global::Proto.Ping.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.BlockingUnaryCall(__Method_Ping, null, options, request);
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Ping.Pong> PingAsync(global::Proto.Ping.Empty request, grpc::Metadata headers = null, global::System.DateTime? deadline = null, global::System.Threading.CancellationToken cancellationToken = default(global::System.Threading.CancellationToken))
      {
        return PingAsync(request, new grpc::CallOptions(headers, deadline, cancellationToken));
      }
      public virtual grpc::AsyncUnaryCall<global::Proto.Ping.Pong> PingAsync(global::Proto.Ping.Empty request, grpc::CallOptions options)
      {
        return CallInvoker.AsyncUnaryCall(__Method_Ping, null, options, request);
      }
      /// <summary>Creates a new instance of client from given <c>ClientBaseConfiguration</c>.</summary>
      protected override CheckClient NewInstance(ClientBaseConfiguration configuration)
      {
        return new CheckClient(configuration);
      }
    }

    /// <summary>Creates service definition that can be registered with a server</summary>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static grpc::ServerServiceDefinition BindService(CheckBase serviceImpl)
    {
      return grpc::ServerServiceDefinition.CreateBuilder()
          .AddMethod(__Method_Ping, serviceImpl.Ping).Build();
    }

    /// <summary>Register service method implementations with a service binder. Useful when customizing the service binding logic.
    /// Note: this method is part of an experimental API that can change or be removed without any prior notice.</summary>
    /// <param name="serviceBinder">Service methods will be bound by calling <c>AddMethod</c> on this object.</param>
    /// <param name="serviceImpl">An object implementing the server-side handling logic.</param>
    public static void BindService(grpc::ServiceBinderBase serviceBinder, CheckBase serviceImpl)
    {
      serviceBinder.AddMethod(__Method_Ping, serviceImpl.Ping);
    }

  }
}
#endregion
